#!/bin/bash

db=`grep "dbname=" $ELECTION_IMPORT/_env | sed "s/dbname="//`
if test "x$db" != "xelections"; then
   echo "ERROR!  Wrong database."
   exit
fi

   v4initialize

#  v4parseNew

   v4elections

   v4compress

   v4corrections
