SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '4180' AND s.subdist = '0'    AND  name = 'Kimberly Gonczy' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://augustatownship.org/clerk/', phone = '734-461-6117, ext 201'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '4180' AND s.subdist = '0'    AND  name = 'Todd Waller' ;
UPDATE v3incumbents SET  status = 'complete', phone = '(734) 461-6117, ext 203'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '4180' AND s.subdist = '0'    AND  name = 'Susan Burek' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://augustatownship.org/treasurer/', phone = '734-461-6117, ext 206'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '4180' AND s.subdist = '0'    AND  name = 'Linda E. Adams' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://augustatownship.org/boards-committees/board-of-trustees/', email = 'trustee1@augustatownship.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '4180' AND s.subdist = '0'    AND  name = 'Keith A. Gipfert' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://augustatownship.org/boards-committees/board-of-trustees/', email = 'trustee2@augustatownship.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '4180' AND s.subdist = '0'    AND  name = 'Michael Green' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://augustatownship.org/boards-committees/board-of-trustees/', email = 'trustee3@augustatownship.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '4180' AND s.subdist = '0'    AND  name = 'Stephanie Prain' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://augustatownship.org/boards-committees/board-of-trustees/', email = 'trustee4@augustatownship.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'vil-cou' AND s.office = 'council' AND s.district = '5660' AND s.subdist = '0'    AND  name = 'Dennis Capozza' ;
UPDATE v3incumbents SET  status = 'complete', phone = '(734) 222-5209'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'vil-cou' AND s.office = 'council' AND s.district = '5660' AND s.subdist = '0'    AND  name = 'Marcus M. Darden' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://bartonhillsvillage.org/boards/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'vil-cou' AND s.office = 'council' AND s.district = '5660' AND s.subdist = '0'    AND  name = 'Mostafa Haitam' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://bartonhillsvillage.org/boards/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'vil-cou' AND s.office = 'council' AND s.district = '5660' AND s.subdist = '0'    AND  name = 'Randolph Perry' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://bartonhillsvillage.org/boards/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '10560' AND s.subdist = '0'    AND  name = 'Michelle McQueer' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-bridgewater.org/township-clerk/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '10560' AND s.subdist = '0'    AND  name = 'Laurie Fromhart' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-bridgewater.org/township-supervisor/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '10560' AND s.subdist = '0'    AND  name = 'Amy Ahrens' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-bridgewater.org/township-treasurer/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '10560' AND s.subdist = '0'    AND  name = 'David C. Faust' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-bridgewater.org/board-of-trustees/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '10560' AND s.subdist = '0'    AND  name = 'R. Geoffrey Oliver' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-bridgewater.org/board-of-trustees/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city' AND s.office = 'mayor' AND s.district = '15020' AND s.subdist = '0'    AND  name = 'Kate Henson' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.city-chelsea.org/government/city_council/index.php', phone = '734-475-1771'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '15020' AND s.subdist = '0'    AND  name = 'Sam Angus' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.city-chelsea.org/government/city_council/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '15020' AND s.subdist = '0'    AND  name = 'Tony Iannelli' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.city-chelsea.org/government/city_council/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '15020' AND s.subdist = '0'    AND  name = 'Felix Stump' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.city-chelsea.org/government/city_council/index.php', phone = '734-475-1771'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '15020' AND s.subdist = '0'    AND  name = 'Eric Keaton' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.city-chelsea.org/government/city_council/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '15020' AND s.subdist = '0'    AND  name = 'George W. Merkel' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.city-chelsea.org/government/city_council/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '15020' AND s.subdist = '0'    AND  name = 'Beth Morris' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.city-chelsea.org/government/city_council/index.php', email = 'jbullerman@city-chelsea.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '8940' AND s.subdist = '0'    AND  name = 'Eric E. Wilkinson' ;
UPDATE v3incumbents SET  status = 'complete', email = 'ewilkinson@chelseaschools.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '8940' AND s.subdist = '0'    AND  name = 'Erin Hunt-Carter' ;
UPDATE v3incumbents SET  status = 'complete', email = 'ehunt-carter@chelseaschools.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '8940' AND s.subdist = '0'    AND  name = 'Glenn Fox' ;
UPDATE v3incumbents SET  status = 'complete', email = 'gfox@chelseaschools.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '8940' AND s.subdist = '0'    AND  name = 'Nicolia Heineman' ;
UPDATE v3incumbents SET  status = 'complete', email = 'nheineman@chelseaschools.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '8940' AND s.subdist = '0'    AND  name = 'Michelle Craig' ;
UPDATE v3incumbents SET  status = 'complete', email = 'mcraig@chelseaschools.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '8940' AND s.subdist = '0'    AND  name = 'Heidi E. Reyst' ;
UPDATE v3incumbents SET  status = 'complete', email = 'hreyst@chelseaschools.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '10050' AND s.subdist = '0'    AND  name = 'Dale Wingerd' ;
UPDATE v3incumbents SET  status = 'complete', web = 'www.miclintonschools.org/page/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '10050' AND s.subdist = '0'    AND  name = 'Monica Renee VanTuyle' ;
UPDATE v3incumbents SET  status = 'complete', phone = '517-605-4076'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '6990' AND s.subdist = '0'    AND  name = 'Tiffany Flinn' ;
UPDATE v3incumbents SET  status = 'complete', email = 'tflinn.columbiaschooldistrict@gmail.com'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city' AND s.office = 'mayor' AND s.district = '22160' AND s.subdist = '0'    AND  name = 'Shawn W. Keough' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.dextermi.gov/government/city_council_directory.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '22160' AND s.subdist = '0'    AND  name = 'Ray Tell' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.dextermi.gov/government/city_council_directory.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '22160' AND s.subdist = '0'    AND  name = 'Wa-Louisa Hubbard' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.dextermi.gov/government/city_council_directory.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '22160' AND s.subdist = '0'    AND  name = 'Pavlo Popov' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.dextermi.gov/government/city_council_directory.php', email = 'ppopov@DexterMI.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '22160' AND s.subdist = '0'    AND  name = 'Sanam Arab' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.dextermi.gov/government/city_council_directory.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '22160' AND s.subdist = '0'    AND  name = 'Joseph R. Semifero' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.dextermi.gov/government/city_council_directory.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '22160' AND s.subdist = '0'    AND  name = 'Daniel Leroy Schlaff' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.dextermi.gov/government/city_council_directory.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '12030' AND s.subdist = '0'    AND  name = 'David Pisano' ;
UPDATE v3incumbents SET  status = 'complete', email = 'Pisanod@dexterschools.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '22180' AND s.subdist = '0'    AND  name = 'Alicia Abbott' ;
UPDATE v3incumbents SET  status = 'complete', web = 'www.dextertownshipmi.gov/township-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '22180' AND s.subdist = '0'    AND  name = 'Karen Nolte' ;
UPDATE v3incumbents SET  status = 'complete', web = 'www.dextertownshipmi.gov/township-board', phone = '734-426-3767'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '22180' AND s.subdist = '0'    AND  name = 'Laura Sanders' ;
UPDATE v3incumbents SET  status = 'complete', web = 'www.dextertownshipmi.gov/township-board', phone = '734-426-3767'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '22180' AND s.subdist = '0'    AND  name = 'Karen Sikkenga' ;
UPDATE v3incumbents SET  status = 'complete', web = 'www.dextertownshipmi.gov/township-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '30520' AND s.subdist = '0'    AND  name = 'Valisa Bristle' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-freedom.org/government/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '30520' AND s.subdist = '0'    AND  name = 'Larry Lindemann' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-freedom.org/government/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '30520' AND s.subdist = '0'    AND  name = 'Rudy T. Layher' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-freedom.org/government/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '30520' AND s.subdist = '0'    AND  name = 'Dennis Earl Huehl' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-freedom.org/government/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '30520' AND s.subdist = '0'    AND  name = 'Daniel L. Schaible' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-freedom.org/government/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '47460' AND s.subdist = '0'    AND  name = 'Ann Kwaske' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://limatownshipmi.gov/board-of-trustees/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '47460' AND s.subdist = '0'    AND  name = 'William VanRiper' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://limatownshipmi.gov/board-of-trustees/', phone = '(734) 475-2246, ext 201'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '47460' AND s.subdist = '0'    AND  name = 'Nanette Havens' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://limatownshipmi.gov/board-of-trustees/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '47460' AND s.subdist = '0'    AND  name = 'Dale Luick' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://limatownshipmi.gov/board-of-trustees/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '47460' AND s.subdist = '0'    AND  name = 'Greg McKenzie' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://limatownshipmi.gov/board-of-trustees/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '21570' AND s.subdist = '0'    AND  name = 'Jennifer Czachorski' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.lincolnk12.org/page/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '21570' AND s.subdist = '0'    AND  name = 'Jennifer LaBombarbe' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.lincolnk12.org/page/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '21570' AND s.subdist = '0'    AND  name = 'JaVon Jason' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.lincolnk12.org/page/board-of-education', email = 'jasonj@lincolnk12.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '21570' AND s.subdist = '0'    AND  name = 'Jason D. Moore' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.lincolnk12.org/page/board-of-education', email = 'moorej@lincolnk12.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '21570' AND s.subdist = '0'    AND  name = 'Matthew Bentley' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.lincolnk12.org/page/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '21570' AND s.subdist = '0'    AND  name = 'Stacy Kind' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.lincolnk12.org/page/board-of-education', email = 'soosa@lincolnk12.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '21570' AND s.subdist = '0'    AND  name = 'Lauren Smith' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.lincolnk12.org/page/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '49120' AND s.subdist = '0'    AND  name = 'Christina Schaible Smith' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://loditownshipmi.org/board-of-trustees-members/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '49120' AND s.subdist = '0'    AND  name = 'Janann Godek' ;
UPDATE v3incumbents SET  status = 'complete', email = 'jan@loditownshipmi.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '49120' AND s.subdist = '0'    AND  name = 'Michelle K. Foley' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://loditownshipmi.org/board-of-trustees-members/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '49120' AND s.subdist = '0'    AND  name = 'Leslie Blackburn' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://loditownshipmi.org/board-of-trustees-members/', email = 'leslie@loditownshipMI.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '49120' AND s.subdist = '0'    AND  name = 'Steve Marsh' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://loditownshipmi.org/board-of-trustees-members/', email = 'steve@loditownshipMI.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '49120' AND s.subdist = '0'    AND  name = 'Alex Matelski' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://loditownshipmi.org/board-of-trustees-members/', email = 'alex@loditownshipMI.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '49120' AND s.subdist = '0'    AND  name = 'Donald A. Rentschler' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://loditownshipmi.org/board-of-trustees-members/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '49780' AND s.subdist = '0'    AND  name = 'Pam Byrnes' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://lyndontownshipmi.gov/township-boards-officials-and-commissions/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '49780' AND s.subdist = '0'    AND  name = 'Kristen Brekke' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://lyndontownshipmi.gov/township-boards-officials-and-commissions/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '50660' AND s.subdist = '0'    AND  name = 'Amelia L. Woods' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://city-manchester.org/village-council/', phone = '(734) 428-7877'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '22380' AND s.subdist = '0'    AND  name = 'Sarah Roth' ;
UPDATE v3incumbents SET  status = 'complete', email = ''   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '22380' AND s.subdist = '0'    AND  name = 'Rebecca Harvey' ;
UPDATE v3incumbents SET  status = 'complete', phone = '734-428-9711'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '50680' AND s.subdist = '0'    AND  name = 'Danell Steele Proctor' ;
UPDATE v3incumbents SET  status = 'complete', email = 'dproctor@twp-manchester.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '50680' AND s.subdist = '0'    AND  name = 'Ronald A. Milkey' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-manchester.org/township-board/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '50680' AND s.subdist = '0'    AND  name = 'Kim Thompson' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-manchester.org/township-board/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '50680' AND s.subdist = '0'    AND  name = 'John Seefeld' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-manchester.org/township-board/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '50680' AND s.subdist = '0'    AND  name = 'Michael Fusilier' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-manchester.org/township-board/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '50680' AND s.subdist = '0'    AND  name = 'Lisa Moutinho' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-manchester.org/township-board/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '50680' AND s.subdist = '0'    AND  name = 'Michael Walter' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp-manchester.org/township-board/', email = 'michaelwalter111@gmail.com'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city' AND s.office = 'mayor' AND s.district = '53920' AND s.subdist = '0'    AND  name = 'Edward J. Kolar III' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanmi.gov/city_hall/city_council/index.php', email = 'edkolar@milanmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '53920' AND s.subdist = '0'    AND  name = 'Jesse Robert Nie' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanmi.gov/city_hall/city_council/index.php', email = 'jessen@milanmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '53920' AND s.subdist = '0'    AND  name = 'Marie Gress' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanmi.gov/city_hall/city_council/index.php', email = 'marieg@milanmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '53920' AND s.subdist = '0'    AND  name = 'Shannon Dare Wayne' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanmi.gov/city_hall/city_council/index.php', email = 'shannonw@milanmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '53920' AND s.subdist = '0'    AND  name = 'Mary C. Kerkes' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanmi.gov/city_hall/city_council/index.php', email = 'maryk@milanmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '53920' AND s.subdist = '0'    AND  name = 'David Snyder' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanmi.gov/city_hall/city_council/index.php', email = 'daves@milanmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '53920' AND s.subdist = '0'    AND  name = 'Matthew Stafford' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanmi.gov/city_hall/city_council/index.php', email = 'matthews@milanmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '23850' AND s.subdist = '0'    AND  name = 'Andrew Cislo' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanareaschools.org/district/board/meet-the-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '23850' AND s.subdist = '0'    AND  name = 'Thomas Faro' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanareaschools.org/district/board/meet-the-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '23850' AND s.subdist = '0'    AND  name = 'Michelle R. Heikka' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanareaschools.org/district/board/meet-the-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '23850' AND s.subdist = '0'    AND  name = 'Sara Meray' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanareaschools.org/district/board/meet-the-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '23850' AND s.subdist = '0'    AND  name = 'Betty Rosen-Leacher' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanareaschools.org/district/board/meet-the-board', email = 'burdetteg@milanareaschools.org', phone = '734-439-5050'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '23850' AND s.subdist = '0'    AND  name = 'Carrie Karvonen-Gutierrez' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanareaschools.org/district/board/meet-the-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '23850' AND s.subdist = '0'    AND  name = 'Cassie Prior' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.milanareaschools.org/district/board/meet-the-board'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '58280' AND s.subdist = '0'    AND  name = 'Kathleen Manley' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-northfield.org/government/township_board_of_trustees/index.php', phone = '(734) 231-1468'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '58280' AND s.subdist = '0'    AND  name = 'Larry Roman' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-northfield.org/government/township_board_of_trustees/index.php', phone = '(734) 645-3932'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '58280' AND s.subdist = '0'    AND  name = 'Jacqueline R. Otto' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-northfield.org/government/township_board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '58280' AND s.subdist = '0'    AND  name = 'Adam Olney' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-northfield.org/government/township_board_of_trustees/index.php', email = 'olneya@northfieldmi.gov', phone = '(734) 449-2880, ext 146'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '58280' AND s.subdist = '0'    AND  name = 'Janet M. Chick' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-northfield.org/government/township_board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '58280' AND s.subdist = '0'    AND  name = 'Jacob Donner' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-northfield.org/government/township_board_of_trustees/index.php', email = 'donnerj@northfieldmi.gov', phone = '(810) 360-9433'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '58280' AND s.subdist = '0'    AND  name = 'Nate Muchow' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-northfield.org/government/township_board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '25980' AND s.subdist = '0'    AND  name = 'Jena Mabrey' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.northvilleschools.org/about/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '25980' AND s.subdist = '0'    AND  name = 'Meredith Riggan Maurer' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.northvilleschools.org/about/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '25980' AND s.subdist = '0'    AND  name = 'Lisa McIntyre' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.northvilleschools.org/about/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '25980' AND s.subdist = '0'    AND  name = 'Ron Frazier' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.northvilleschools.org/about/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '25980' AND s.subdist = '0'    AND  name = 'Carin Meyer' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.northvilleschools.org/about/board-of-education', phone = '734-301-2451'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '25980' AND s.subdist = '0'    AND  name = 'Kim Campbell-Voytal' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.northvilleschools.org/about/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '25980' AND s.subdist = '0'    AND  name = 'Melissa Stuart' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.northvilleschools.org/about/board-of-education'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Matthew Maciag' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pinckneypirates.org/page/school-board-new'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Bethany Mohr' ;
UPDATE v3incumbents SET  status = 'complete', web = ''   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Rudy Gome' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pinckneypirates.org/page/school-board-new', email = ''   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Ashley Voss' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pinckneypirates.org/page/school-board-new', email = ''   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Bill Wearne' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pinckneypirates.org/page/school-board-new'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Gayle Hurn' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pinckneypirates.org/page/school-board-new'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Melissa Mueller' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pinckneypirates.org/page/school-board-new'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28140' AND s.subdist = '0'    AND  name = 'Amanda Winningham' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pinckneypirates.org/page/school-board-new'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-park' AND s.district = '64560' AND s.subdist = '0'    AND  name = 'Sean Reilly' ;
UPDATE v3incumbents SET  status = 'complete', phone = '(734) 822-2120'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '64560' AND s.subdist = '0'    AND  name = 'Trish Reilly' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.pittsfield-mi.gov/351/Supervisors-Office', email = 'supervisor@pittsfield-mi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '64560' AND s.subdist = '0'    AND  name = 'David Brabec' ;
UPDATE v3incumbents SET  status = 'complete', email = 'brabecd@pittsfield-mi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '64560' AND s.subdist = '0'    AND  name = 'Courtney Mills' ;
UPDATE v3incumbents SET  status = 'complete', email = 'Millsc@pittsfield-mi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28560' AND s.subdist = '0'    AND  name = 'Sebastien Ostertag' ;
UPDATE v3incumbents SET  status = 'complete', email = 'Aamina.Ahmed@pccsk12.com'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '28560' AND s.subdist = '0'    AND  name = 'Judy Westra' ;
UPDATE v3incumbents SET  status = 'complete', email = 'Judy.Westra@pccsk12.com'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '71130' AND s.subdist = '0'    AND  name = 'Del Wensley' ;
UPDATE v3incumbents SET  status = 'complete', phone = '248-9349-1690, ext 9'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '71130' AND s.subdist = '0'    AND  name = 'Gary Whittaker' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.salem-mi.org/government/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '71130' AND s.subdist = '0'    AND  name = 'Bruce Reeve' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.salem-mi.org/government/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71130' AND s.subdist = '0'    AND  name = 'John Daniel' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.salem-mi.org/government/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71130' AND s.subdist = '0'    AND  name = 'Reggie DeLuca' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.salem-mi.org/government/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71130' AND s.subdist = '0'    AND  name = 'TJ McLaughlin' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.salem-mi.org/government/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71130' AND s.subdist = '0'    AND  name = 'David Trent' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.salem-mi.org/government/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city' AND s.office = 'mayor' AND s.district = '71140' AND s.subdist = '0'    AND  name = 'Brian D. Marl' ;
UPDATE v3incumbents SET  status = 'complete', email = 'bmarl@salinemi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '71140' AND s.subdist = '0'    AND  name = 'Janet Dillon' ;
UPDATE v3incumbents SET  status = 'complete', email = 'jdillon@salinemi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '71140' AND s.subdist = '0'    AND  name = 'Dean Benjamin Girbach' ;
UPDATE v3incumbents SET  status = 'complete', email = 'dbgirbach@salinemi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '71140' AND s.subdist = '0'    AND  name = 'Nicole Rice' ;
UPDATE v3incumbents SET  status = 'complete', email = 'nrice@salinemi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '71140' AND s.subdist = '0'    AND  name = 'Jim Dell\'Orco' ;
UPDATE v3incumbents SET  status = 'complete', email = 'jdellorco@salinemi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '71140' AND s.subdist = '0'    AND  name = 'Jenn Harmount' ;
UPDATE v3incumbents SET  status = 'complete', email = 'jharmount@salinemi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '30660' AND s.subdist = '0'    AND  name = 'M. Aramide Boatswain' ;
UPDATE v3incumbents SET  status = 'complete', web = '', email = '', phone = '', address = ''   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '71160' AND s.subdist = '0'    AND  name = 'Kelly Marion' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://salinetownship.org/board-members'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '71160' AND s.subdist = '0'    AND  name = 'James C. Marion' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://salinetownship.org/board-members'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '71160' AND s.subdist = '0'    AND  name = 'Jennifer Zink' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://salinetownship.org/board-members'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71160' AND s.subdist = '0'    AND  name = 'Tom P. Hammond' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://salinetownship.org/board-members', email = 'hammondtom560@gmail.com'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71160' AND s.subdist = '0'    AND  name = 'Robert J. Marion' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://salinetownship.org/board-members', email = 'dean34744@gmail.com', phone = '(734)260-2337'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '71940' AND s.subdist = '0'    AND  name = 'Jessica M. Flintoft' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sciotownshipmi.gov/democracy/board-of-trustees-170'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '71940' AND s.subdist = '0'    AND  name = 'Jillian Michele Kerry' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sciotownshipmi.gov/democracy/board-of-trustees-171'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '71940' AND s.subdist = '0'    AND  name = 'Ryan Yaple' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sciotownshipmi.gov/democracy/board-of-trustees-172'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71940' AND s.subdist = '0'    AND  name = 'Kathleen Brant' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sciotownshipmi.gov/democracy/board-of-trustees-173'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71940' AND s.subdist = '0'    AND  name = 'Judy DeVooght Moenck' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sciotownshipmi.gov/democracy/board-of-trustees-174'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71940' AND s.subdist = '0'    AND  name = 'Kathleen Knol' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sciotownshipmi.gov/democracy/board-of-trustees-175'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '71940' AND s.subdist = '0'    AND  name = 'John W. Reiser' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sciotownshipmi.gov/democracy/board-of-trustees-176'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '72760' AND s.subdist = '0'    AND  name = 'Michelle Mrocko' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sharontownship.org/boards_and_commissions/board_of_trustees/members.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '72760' AND s.subdist = '0'    AND  name = 'Katharyn Spiegel' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sharontownship.org/boards_and_commissions/board_of_trustees/members.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '72760' AND s.subdist = '0'    AND  name = 'Brian Brickley' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sharontownship.org/boards_and_commissions/board_of_trustees/members.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '72760' AND s.subdist = '0'    AND  name = 'Anna K. Harvey' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sharontownship.org/boards_and_commissions/board_of_trustees/members.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '72760' AND s.subdist = '0'    AND  name = 'Trudi Cooper' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.sharontownship.org/boards_and_commissions/board_of_trustees/members.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '32250' AND s.subdist = '0'    AND  name = 'Michele Lake' ;
UPDATE v3incumbents SET  status = 'complete', email = 'lakem@slcs.us'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '32250' AND s.subdist = '0'    AND  name = 'Ann Rimanelli' ;
UPDATE v3incumbents SET  status = 'complete', email = 'rimanellia@slcs.us'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '33030' AND s.subdist = '0'    AND  name = 'Jill Marie Ogden' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.panthernet.net/boardofeducation/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '33030' AND s.subdist = '0'    AND  name = 'Cynthia Sue Lance' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.panthernet.net/boardofeducation/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '33030' AND s.subdist = '0'    AND  name = 'Kary Gee' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.panthernet.net/boardofeducation/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '33030' AND s.subdist = '0'    AND  name = 'Keven Numinen' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.panthernet.net/boardofeducation/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '33030' AND s.subdist = '0'    AND  name = 'Carrie E. Graham' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.panthernet.net/boardofeducation/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '33030' AND s.subdist = '0'    AND  name = 'Erin L. Gancer' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.panthernet.net/boardofeducation/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '33030' AND s.subdist = '0'    AND  name = 'Richard D. Ramalia III' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.panthernet.net/boardofeducation/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-park' AND s.district = '77560' AND s.subdist = '0'    AND  name = 'Matthew Yahyai' ;
UPDATE v3incumbents SET  status = 'complete', email = 'superiorparks@superior-twp.org', phone = '(734) 480-5502'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '77560' AND s.subdist = '0'    AND  name = 'Emily Dabish Yahkind' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://superiortownship.org/government/staff-directory/', email = 'edy@superior-twp.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '77560' AND s.subdist = '0'    AND  name = 'Sarah Devereaux' ;
UPDATE v3incumbents SET  status = 'complete', email = 'sdevereaux@superior-twp.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '77560' AND s.subdist = '0'    AND  name = 'Dana Greene Jr.' ;
UPDATE v3incumbents SET  status = 'complete', email = 'dgreene@superior-twp.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '77560' AND s.subdist = '0'    AND  name = 'Brenda L. McKinney' ;
UPDATE v3incumbents SET  status = 'complete', email = 'brendamckinney@superior-twp.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '77560' AND s.subdist = '0'    AND  name = 'Ken Schwartz' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://superiortownship.org/government/staff-directory/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '77800' AND s.subdist = '0'    AND  name = 'Douglas Jackson' ;
UPDATE v3incumbents SET  status = 'complete', email = 'clerk@sylvantownshipmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '77800' AND s.subdist = '0'    AND  name = 'Sandra J. Egeler' ;
UPDATE v3incumbents SET  status = 'complete', email = 'treasurer@sylvantownshipmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '77800' AND s.subdist = '0'    AND  name = 'Sandra E. Schulze' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://sylvantownshipmi.gov/trustees/', email = 'sschulze@sylvantownshipmi.gov'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '85100' AND s.subdist = '0'    AND  name = 'Barbara Calleja' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp.webster.mi.us/government/boards___commissions/board_of_trustees.php', email = 'tbrovont@webstermi.us'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '85100' AND s.subdist = '0'    AND  name = 'L. Michael DeAngelo' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp.webster.mi.us/government/boards___commissions/board_of_trustees.php', email = 'mdeangelo@webstermi.us'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '85100' AND s.subdist = '0'    AND  name = 'John Scharf' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp.webster.mi.us/government/boards___commissions/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '85100' AND s.subdist = '0'    AND  name = 'Dan Munzel' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp.webster.mi.us/government/boards___commissions/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '85100' AND s.subdist = '0'    AND  name = 'Brant Savander' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp.webster.mi.us/government/boards___commissions/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '85100' AND s.subdist = '0'    AND  name = 'Jeff Harms' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp.webster.mi.us/government/boards___commissions/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '85100' AND s.subdist = '0'    AND  name = 'Shelly Vrsek' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://twp.webster.mi.us/government/boards___commissions/board_of_trustees.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '36330' AND s.subdist = '0'    AND  name = 'Laura Schwennesen' ;
UPDATE v3incumbents SET  status = 'complete', web = '', email = '', phone = '', address = ''   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '89100' AND s.subdist = '0'    AND  name = 'Kayleigh Zupi' ;
UPDATE v3incumbents SET  status = 'complete', email = 'Clerk@Twp-York.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '89100' AND s.subdist = '0'    AND  name = 'Chuck Tellas' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-york.org/departments/supervisor_s_office/index.php', email = 'dludwig@twp-york.org', phone = '734-439-8842 x5'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '89100' AND s.subdist = '0'    AND  name = 'Sally B. Louis' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-york.org/departments/treasurer_s_office/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89100' AND s.subdist = '0'    AND  name = 'Thomas Gary' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-york.org/government/boards_commissions_/board_of_trustees/board_members.php', email = 'Tgary10445@aol.com'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89100' AND s.subdist = '0'    AND  name = 'John Hargrove' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-york.org/government/boards_commissions_/board_of_trustees/board_members.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89100' AND s.subdist = '0'    AND  name = 'Jason D. McGovern' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-york.org/government/boards_commissions_/board_of_trustees/board_members.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89100' AND s.subdist = '0'    AND  name = 'Helen Neill' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://www.twp-york.org/government/boards_commissions_/board_of_trustees/board_members.php', email = 'hln321@yahoo.com'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city' AND s.office = 'mayor' AND s.district = '89140' AND s.subdist = '0'    AND  name = 'Nicole Brown' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://cityofypsilanti.com/323/Elected-Officials'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '89140' AND s.subdist = '1'    AND  name = 'Michelle (Me\' Chelle) King' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://cityofypsilanti.com/323/Elected-Officials'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '89140' AND s.subdist = '2'    AND  name = 'Steven Wilcoxen' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://cityofypsilanti.com/323/Elected-Officials'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '89140' AND s.subdist = '3'    AND  name = 'Amber Fellows' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://cityofypsilanti.com/323/Elected-Officials', phone = '(734) 219-3798'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '89140' AND s.subdist = '1'    AND  name = 'Roland Tooson' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://cityofypsilanti.com/323/Elected-Officials'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '89140' AND s.subdist = '2'    AND  name = 'Patrick McLean' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://cityofypsilanti.com/323/Elected-Officials'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '89140' AND s.subdist = '3'    AND  name = 'Desirae Simmons' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://cityofypsilanti.com/323/Elected-Officials'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '36630' AND s.subdist = '0'    AND  name = 'Meredith Schindler' ;
UPDATE v3incumbents SET  status = 'complete', web = '', email = '', phone = '', address = ''   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-park' AND s.district = '89160' AND s.subdist = '0'    AND  name = 'Lawrence W. Johnson' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://ypsitownship.org/government/boards___commissions/park_commission/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '89160' AND s.subdist = '0'    AND  name = 'Stan Eldridge' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://ypsitownship.org/departments/treasurers_office/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89160' AND s.subdist = '0'    AND  name = 'Karen Lovejoy Roe' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://ypsitownship.org/government/boards___commissions/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89160' AND s.subdist = '0'    AND  name = 'John P. Newman II' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://ypsitownship.org/government/boards___commissions/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89160' AND s.subdist = '0'    AND  name = 'Gloria Peterson' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://ypsitownship.org/government/boards___commissions/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v3seats      AS s   LEFT JOIN v3incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '89160' AND s.subdist = '0'    AND  name = 'LaResha Thornton' ;
UPDATE v3incumbents SET  status = 'complete', web = 'https://ypsitownship.org/government/boards___commissions/board_of_trustees/index.php'   WHERE seat_id IN (SELECT @seatid);
