SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty' AND s.office = 'atty' AND s.district = '81' AND s.subdist = '0'    AND  name = 'Eli Savit' ;
UPDATE v4incumbents SET  Status = 'complete', address = '200 N. Main, Suite 320, Ann Arbor, MI 48104'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty' AND s.office = 'clerkreg' AND s.district = '81' AND s.subdist = '0'    AND  name = 'Lawrence Kestenbaum' ;
UPDATE v4incumbents SET  Status = 'complete', address = '200 North Main St, Suite 120, Ann Arbor, MI 48104'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty' AND s.office = 'drain' AND s.district = '81' AND s.subdist = '0'    AND  name = 'Gretchen D. Driskell' ;
UPDATE v4incumbents SET  Status = 'complete', email = 'drains@washtenaw.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty' AND s.office = 'sheriff' AND s.district = '81' AND s.subdist = '0'    AND  name = 'Alyshia M. Dyer' ;
UPDATE v4incumbents SET  Status = 'complete', email = 'sheriffinfo@washtenaw.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty' AND s.office = 'treas' AND s.district = '81' AND s.subdist = '0'    AND  name = 'Latitia Lamelle Sharp' ;
UPDATE v4incumbents SET  Status = 'complete', address = '200 N Main Street Suite 200, Ann Arbor, MI 48104'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '1'    AND  name = 'Jason Maciejewski' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '2'    AND  name = 'Crystal Lyte' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '3'    AND  name = 'Shannon Beeman' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '4'    AND  name = 'Caroline L. Sanders' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '5'    AND  name = 'Justin D. Hodge' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '6'    AND  name = 'Annie Somerville' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '7'    AND  name = 'Andy LaBarre' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '8'    AND  name = 'Yousef Rabhi' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'cnty-com' AND s.office = '' AND s.district = '81' AND s.subdist = '9'    AND  name = 'Katie Scott' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city' AND s.office = 'mayor' AND s.district = '3000' AND s.subdist = '0'    AND  name = 'Christopher Taylor' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'https://www.a2gov.org/city-council/mayor-christopher-taylor/'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '1'    AND  name = 'Lisa Disch' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '2'    AND  name = 'Jon Mallek' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council', phone = '734-418-8143', address = '301 E. Huron Street, Ann Arbor, MI 48104'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '3'    AND  name = 'Travis Radina' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '4'    AND  name = 'Jen Eyer' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '5'    AND  name = 'Erica Briggs' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '1'    AND  name = 'Cynthia Harrison' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '2'    AND  name = 'Chris Watson' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '3'    AND  name = 'Ayesha Ghazi Edwin' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '4'    AND  name = 'Dharma Akmon' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'city-cou' AND s.office = '' AND s.district = '3000' AND s.subdist = '5'    AND  name = 'Jenn Cornell' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'www.a2gov.org/city-council'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '2820' AND s.subdist = '0'    AND  name = 'Don Wilkerson' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '2820' AND s.subdist = '0'    AND  name = 'Leslie Wilkins' ;
UPDATE v4incumbents SET  Status = 'complete', phone = '734-478-0355'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '2820' AND s.subdist = '0'    AND  name = 'Glynda T. Wilks' ;
UPDATE v4incumbents SET  Status = 'complete', phone = '734-478-1053'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '2820' AND s.subdist = '0'    AND  name = 'Susan Baskett' ;
UPDATE v4incumbents SET  Status = 'complete', phone = '734-478-0392'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '2820' AND s.subdist = '0'    AND  name = 'Rima Mohammad' ;
UPDATE v4incumbents SET  Status = 'complete', phone = '734-478-0048'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '2820' AND s.subdist = '0'    AND  name = 'Susan Ward Schmidt' ;
UPDATE v4incumbents SET  Status = 'complete', phone = '734-478-0916'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'schl-cou' AND s.office = '' AND s.district = '2820' AND s.subdist = '0'    AND  name = 'Torchio Feaster' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-clerk' AND s.district = '3020' AND s.subdist = '0'    AND  name = 'Kristine Bolhuis' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'aatwp.org/township-government/departments/clerk', email = 'clerk@aatwp.org', phone = '734-663-3418, ext 108', address = '3792 Pontiac Trail Ann Arbor, MI  48105'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-super' AND s.district = '3020' AND s.subdist = '0'    AND  name = 'Diane O\'Connell' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town' AND s.office = 'town-treas' AND s.district = '3020' AND s.subdist = '0'    AND  name = 'Carlene Colvin-Garcia' ;
UPDATE v4incumbents SET  Status = 'complete'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '3020' AND s.subdist = '0'    AND  name = 'John E. Allison' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'https://aatwp.org/trustees/', email = 'trustees@aatwp.org'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '3020' AND s.subdist = '0'    AND  name = 'Della DiPietro' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'https://aatwp.org/trustees/', email = 'trustees@aatwp.org', phone = '734-663-3418', address = '3792 Pontiac Trail Ann Arbor, MI 48105'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '3020' AND s.subdist = '0'    AND  name = 'Eric Kaldjian' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'https://aatwp.org/trustees/', email = 'trustees@aatwp.org', phone = '734-663-3418', address = '3792 Pontiac Trail Ann Arbor, MI 48105'   WHERE seat_id IN (SELECT @seatid);
SELECT i.seat_id INTO @seatid   FROM      v4seats      AS s   LEFT JOIN v4incumbents AS i ON (i.seat_id = s.id)  WHERE  s.org = 'town-cou' AND s.office = 'council' AND s.district = '3020' AND s.subdist = '0'    AND  name = 'Peter Kotila' ;
UPDATE v4incumbents SET  Status = 'complete', web = 'https://aatwp.org/trustees/', email = 'trustees@aatwp.org'   WHERE seat_id IN (SELECT @seatid);
